### ISSUE TITLE
Error in if (theme$panel.ontop) { : argument is of length zero

### ISSUE THREAD

**Issue by ghost** [diegovalle/mxmaps#11]
Hey Diego, when I run your examples like:

```r
df_mxmunicipio$value <-  df_mxmunicipio$indigenous / df_mxmunicipio$pop * 100
mxmunicipio_choropleth(df_mxmunicipio, num_colors = 1,
                       zoom = c(31001:31106,30002:30212),
                       title = "Percentage of the population that self-identifies\nas indigenous in Yucatán and Veracruz",
                       show_states = FALSE,
                       legend = "%")
```

I get this error:

Error in if (theme$panel.ontop) { : argument is of length zero.

Do you have any idea how to fix it!

Gracias!

**Comment by diegovalle** [comment]
Could you update to the latest versions of ggplot2 and choroplethr

```r
update.packages(c("ggplot2", "choroplethr"))
```

if this doesn't work could you please paste the output of `sessionInfo()`. This error looks like you are using an old version of ggplot2

**Comment by ghost** [comment]
Listo ya funciono muchas gracias, si no fuera mucha molestia tengo una gran duda.

Me gustaría hacer zoom en un estado en un mapa de municipios. Funciona con el mapa de los estados pero me sale este error con este código:

df_mxmunicipio$value <- as.factor(sample(letters[1:2], 2457, replace = TRUE) )
gg<-mxmunicipio_choropleth(df_mxmunicipio, zoom = "01")
gg

Error: all(zoom %in% unique(self$map.df$region)) is not TRUE

Muchísimas gracias!

**Comment by ghost** [comment]
Ya lo logre, vi que tenia que poner una lista de todos los códigos “region” del estado en el argumento zoom.

Gracias de todas formas!!

Jeffrey
