### ISSUE TITLE
integración mxmaps + inegiR

### ISSUE THREAD

**Issue by Eflores89** [diegovalle/mxmaps#7]
Diego, veo que hiciste una función para integrar una llamada a inegiR y hacer un chroloplethr... **muy bueno**\- dejaré morir `mexicomapR`, tienes mucho mejor elaborado esto y no quisiera duplicar y hacerlo peor. 

Por otro lado, estoy actualizando algunas funciones del paquete y entre los cambios quiero tu opinión (para no afectar la integración entre ambos paquetes): 
- Voy a cambiar los nombres de los resultados de las funciones que traen datos por estados. Un ejemplo es el del PIB estatal: cambiaré de "Aguascalientes" a "AGS", que se me hace mucho más fácil de manejar y leer. No creo, pero si estas usando alguno de estos avísame para ver si dejo una opción para mantener nombres previos y no afectarte. 
- Tengo un indicador (y quisiera agregar más) a nivel "ciudad" que pública el INEGI, me imagino es el área metropolitana pero igual quiero ver si te afecta en algún sentido. 
- Voy a tomar tu catálogo de región-estado, para que los indicadores estatales de inegiR se puedan traducir fácilmente a un df que pueda leer `mxmaps`. Esta es la mejor opción, ¿no?
- Hay una función nueva: `denue_grid`, [aquí](https://github.com/Eflores89/inegiR/blob/master/R/FuncionesAuxiliares_denue.R) que te puede interesar (aunque tal vez no necesariamente para este proyecto). 

Cualquier otro tema que creas sirva para integrar ambos paquetes, adelante! Saludos.

**Comment by Eflores89** [comment]
**never mind** lo del catálogo, veo que tienes uno bien armado. Publicaré así entonces.

**Comment by diegovalle** [comment]
Está genial, no creo que me afecte, por el momento mxmaps sólo usa la función de serie_inegi. Pero de todas maneras es mejor hacer los cambios ahorita que todavía está en alpha y se puede cambiar la interfaz fácilmente. De todas maneras reviso inegiR y te aviso si hay alguna incompatibilidad.
