### ISSUE TITLE
Center map titles

### ISSUE THREAD

**Issue by diegovalle** [diegovalle/mxmaps#8]
Looks like the bottom map is getting incorrectly cropped

```r
library(mxmaps)
df_mxmunicipio$value <-  df_mxmunicipio$indigenous / df_mxmunicipio$pop * 100
mxmunicipio_choropleth(df_mxmunicipio, num_colors = 1,
                       zoom = c(31001:31106,30002:30212),
                       title = "Percentage of the population that self-identifies\nas indigenous in Yucatán and Veracruz",
                       show_states = FALSE,
                       legend = "%")
```

**Comment by PinkyPao** [comment]
Hola Diego,

Primero que nada, felicidades por un desarrollo así de bueno y útil. Por otra parte, quería preguntarte si hay alguna forma de modificar los aesthetics de las gráficas generadas con tu paquete, por ejemplo que la leyenda se pueda hacer más pequeña o eliminarla, misma situación con el título. 

Gracias

**Comment by diegovalle** [comment]
Hola PinkyPao,

La sección de issues es para reportar bugs del programa, me puedes enviar un email con tu pregunta.
