### ISSUE TITLE
Pins en el mapa

### ISSUE THREAD

**Issue by ghost** [diegovalle/mxmaps#9]
Buen día,

Antes que nada muchas gracias por la librería, me ha servido de mucho y me parece increible.
¿Existe alguna manera de colocar pins en el mapa?

Muchas Gracias

**Comment by diegovalle** [comment]
Hola,

El issue tracker de GitHub es para reportar bugs o pedir nuevos features. Si necesitas ejemplos de como usar el paquete siempre me puedes contactar por email o en twitter.

```{r}
library(leaflet)
library(mxmaps)

head(df_mxmunicipio)
m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=head(df_mxmunicipio)$long, lat=head(df_mxmunicipio)$lat, 
             popup=head(df_mxmunicipio)$municipio_name)
m  # Print the map
```
